spring.config.import=optional:file:.env[.properties]

spring.application.name=rag-from-scratch-java
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=raguser
spring.datasource.password=ragpassword
openai.api.key=${OPENAI_API_KEY}